### PR TITLE
Adds SqlValue.Jsonb

### PR DESCRIPTION
**Pull request by aaronmu**
https://www.npgsql.org/doc/faq.html#a-namejsonbim-trying-to-write-a-jsonb-type-and-am-getting-column-xxx-is-of-type-jsonb-but-expression-is-of-type-texta

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Looks good to me, let me know when it is ready to merge ;)

**Comment by aaronmu** [comment]
@Zaid-Ajaj mapping to a Jsonb column doesn't work because Sql.readValue thinks it's a string. Currently no idea how to get around this.

**Comment by Zaid-Ajaj** [comment]
`SqlDataReader` (the default client for mssql) provides meta data and types for the columns of the result set being returned, see [SqlDataReader.GetSchemaTable](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldatareader.getschematable?view=netframework-4.7.2). I think `NpgsqlDataReader` might have the same, you look in that direction. If time permits, I will look into it soon...

**Comment by Zaid-Ajaj** [comment]
@aaronmu In your test roundtrip, can you try cast the resulting scalar into the `jsonb` type? i.e.
```fs
Sql.query "select @json::jsonb`
```
Also see [enabling `Json.NET`](https://www.npgsql.org/doc/types/jsonnet.html#jobjectjarray) on the converter, maybe that will work

**Comment by rfrerebe** [comment]
Hello,

Testing a round trip can't work because  because [Npgsql default handling of Json](http://www.npgsql.org/doc/types/jsonnet.html) is string.

>  Out of the box, Npgsql allows reading and writing these types as **strings** and provides no further processing to avoid taking a dependency on an external JSON library, forcing Npgsql users to serialize and deserialize JSON values themselves

I haven't tested it in C#, but from the documentation, my understanding is that the same round trip test would fail with Npgsql (ie : you send a Jsonb, but you will receive a string).

From an Npgsql.Fsharp point of view, you currently defined Jsonb as **Jsonb of string**, so when [reading it](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Sql.fs#L258-L262) it's identified as a string and not as a jsonb, but I would say that real root cause is what I mentioned above.

I see 3 solutions :
1.  Use a converter from SqlValue.String to SqlValue.Jsonb (ugly but satisfying from a roundtrip point of view)
2. Leave it as is but change your tests (roundtrip will never work, but you can still insert data as Jsonb and read it as text)
3. Define Jsonb as **Jsonb of JObject** and take some dependencies with [Json.NET](https://www.nuget.org/packages/Newtonsoft.Json/) and [Npgsql.Json.NET](https://www.nuget.org/packages/Npgsql.Json.NET/) in Npgsql.Fsharp.

@Zaid-Ajaj What do you think about this ?
I would personally prefer the second option as it's closer from Npgsql position.

**Comment by rfrerebe** [comment]
Hello,

Solution 2 is ok for me.
Tests just needs to be amended (a create table +insert +select) instead of the roundtrip test.
@aaronmu can you amend your PR, please ?

Thanks

**Comment by rfrerebe** [comment]
Also, I am now reluctant to bind to Json.NET, as [MSFT](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/roadmap/README.md) [just](https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/) [annonced](https://github.com/dotnet/announcements/issues/90) that they were working on a replacement working with Span to minimize allocation (and increase speed)

**Comment by Zaid-Ajaj** [comment]
@rfrerebe I agree that minimizing the deps is best in general and I wanted for this library only to be a thin layer on top of the base library.

**Pull request merged**
