### PR TITLE
Change in optional property mapping

### PR DESCRIPTION
**Pull request by gmlion**
https://github.com/Zaid-Ajaj/Npgsql.FSharp/issues/19

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi there @gmlion, does this actually solve the problem of the casting exception? I think not. When you map 
```
SqlValue.Null -> box (None)
```
the underlying type of `box (None)` will still be `Option<obj>` instead of a generic  `Option<'t>` where `'t` is the type of of the optional record field. I think you need to do some manual work:
```fs
| SqlValue.Null -> 
  match fieldProperty.Type.FullName with 
  | "System.Int16" -> Option<int16>.None
  | "System.Int32" -> Option<int>.None 
  | "System.Int64" -> Option<int64>.None
  | "System.String" -> Option<string>.None 
  | "System.Boolean" -> Option<bool>.None 
  | "System.Decimal" -> Option<decimal>.None 
  | "System.Double" -> Option<float>.None
  | (* etc. *) -> 
  |> box
```
Yeah that's why I don't like automatic parsing much with this, making it a full ORM, there just too many gotcha's

**Comment by gmlion** [comment]
Hi @Zaid-Ajaj, thank you for your time.

I think the casting exception was casued by line 639
`Some <| (FSharpValue.MakeRecord(typeof<'a>, args) :?> 'a)`
where, if I understand correctly, the casting targets the entity record and not the single property.

Also, I think, all the properties are boxed to object and so they loose their underlying type (and it explains why a dynamic cast is needed).
Furthermore, Option.None internal representation is null (https://stackoverflow.com/questions/52827260/why-none-change-to-null-automatically-in-f) so the dynamic casting from Option<'t>.None to Option.None work flawlessly

**Comment by gmlion** [comment]
Yes, I stumbled upon the aforementioned exception while using the library, so AFAIK as it stands now it is uncapable of mapping a null sql value to an Option.None, while with this commit it seems to work correctly. The current implementation maps to Option.None only a missing database column, but I think this use case is quite uncommon. Also, that's not how it is documented in the README:

`You can turn a field into an option if it's defined as "Nullable" in your table`

**Comment by Zaid-Ajaj** [comment]
@gmlion Sounds good to me, if this PR is ready let me know and I will merge it

I will also do some more testing to make sure the parsing works for multiple use-cases and make sure the docs align to the actual functionality

Thanks a lot for this :smile:

**Comment by gmlion** [comment]
You're welcome, thank you for the library. Unless you come up with a better approach for the (lack of) typing, I think the PR can be merged and is a step in the right direction.

**Pull request closed without merging**
