### PR TITLE
Rewrite: Introducing V2

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
For a while now I have been thinking about the API of Npgsql.FSharp and the possibilities it allows. But there problems that me rethink how the API should behave. Here I will explain my thoughts and the solutions:

### Problems with `Sql.executeReader`
Using the `Sql.executeReader` function especially made things really easy. However, there were some problems with it. *Always* using optional return types: it **skipped** rows that it could not handle! When using `Sql.readString`, `Sql.readInt`, `Sql.readBool` etc. They will return `None`  when the type of the column doesn't match the function or when the column *doesn't exist*. The latter being a programmer error, it should fail with an exception saying that the required column missing but instead that row is just skipped. This is not ideal because if you made a change in the database, the function will not fail but just return an empty list instead. 

### Problems with `Sql.read{ColummType}` 
As mentioned above, these functions do not make the distinction between reading a `NULL` column or a column that doesn't exist which can be problematic. Another problem is that these **search**  through all the columns on every row to find the value they are looking for. 

### Static analysis problems:
Since functions of the form `Sql.read{ColummType}` do not make the distinction between `NULL` columns and columns that don't exists, they do not provide enough information for [Npgsql.FSharp.Analyzer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) to proper analysis. For example when using nullable-column reading function on non-nullable column type. With this release, I intend to make the static analysis even more exact and correct for better developer experience. 

### Too many overloads and variants of all functions
For each kind of function, there was the default implementation, the safe, the async and the safe async variants! This was just too much. In this release, *all* the functions are safe by default with only a synchronous and asynchronous variants. for example `Sql.execute` and `Sql.executeAsync`.

Not to forget the `Task` based methods that were used to provide a cancellation token and their variants. These are now removed as well. When you want to provide a `CancellationToken` from task-based workflows, you can now use `Sql.cancellationToken yourCT` as an optional configuration function.

### Automatic type-resolution via Reflection
Removed, use `Sql.execute` directly and read the columns explicitly. I want to keep the library as simple as possible

### Solution

Now introducing a generic `Sql.execute` function that will take a specialized `RowReader` (a small wrapper on top of `NpgsqlReader`) that will make the reading correct and fast. This `RowReader` caches the indeces of columns and their types only once and reuses the index of a column when being searched for:
```fs
let users() : Result<User list, exn> = 
    Sql.connect connectionString
    |> Sql.query "SELECT * FROM users WHERE login_attempts > @attempts"
    |> Sql.parameters [ "attempts", Sql.int 5 ]  
    |> Sql.execute (fun read-> {
           userId =  read.int "user_id" 
           username = read.text "username" 
           firstName = read.textOrNull "first_name"
           active = read.bit "is_active"  
        })
```

### Your Thoughts
Please me know what think! You can already use the new library as it is published to nuget in beta release: `2.0.0-beta`.

### CODE REVIEW

**Comment by ericsampson** [comment]
Zaid, I like the direction, but I find the `typeOrNull` convention pretty verbose and also a little strange-sounding - because `typeOrNull` makes it sound like you will get a `dbNull` back, but it's really talking about the db column being nullable. Any thoughts? I'm trying to think of something different but haven't had much luck. The one idea that I did have which I kind of prefer is `typeOrNone`, because that's more indicative of what will happen and so more intuitive to me. Or the other idea I don't like quite as much, but is more similar to the original, is `read.nullableType`. Cheers!

**Comment by ericsampson** [comment]
Also, how do you provide a default value in this version? That got dropped from the readme.

**Comment by Zaid-Ajaj** [comment]
Hello @ericsampson! I certainly was debating between a couple of variants of the read functions like `typeOrNull`, `nullableType`, `typeOrNone`, `typeOpt` and `optionalType` and I realized that all of these are good depending on how you want to interpret them: `typeOrNone` says more about the output it returns and `typeOrNull` says more about the column it is trying to read. The others are somewhere in between. Users will always have preferences towards one or other and I though they were both good so I tossed a coin and chose one. 

> Also, how do you provide a default value in this version? That got dropped from the readme.

You mean when reading nullable columns? just use `defaultArg` because you getting an `Option<'t>` back.  Something like this:

```fs
type User = {
    Id: int
    FirstName: string
    LastName: string
}

let getAllUsers() : Result<User list, exn> =
    defaultConnection
    |> Sql.connectFromConfig
    |> Sql.query "SELECT * FROM users"
    |> Sql.execute (fun read -> {
        Id = read.int "user_id"
        FirstName = read.text "first_name"
        LastName = defaultArg (read.textOrNull "last_name") ""
    })
```
I will try to add later to the docs when time permits (PRs would be nice though :smile:) thanks a lot for the feedback 🙏

**Comment by ericsampson** [comment]
Hi @Zaid-Ajaj ! Thanks for the explanation—I still feel that `typeOrNone` is really the preferable option; for someone reading the code it’s much more obvious what’s going on; otherwise it could be truly returning `null` to the caller, especially for people who are newer to F#. When I talked to a couple folks in this boat, that’s what they assumed `typeOrNull` would be doing—passing the null/dbnull back to the caller. 

I’ll make a PR for the doc

Thanks for the redesign, it’s a great improvement (other than my concern above) 👍

**Comment by ericsampson** [comment]
I guess I could make a PR to add aliases of `typeOrNone` for the types? Would you accept such a PR Zaid?

**Comment by Zaid-Ajaj** [comment]
@ericsampson I really appreciate your willingness to make this an even better library, especially for F# beginners. I probably have left this PR open for little longer so that more people can give me advice on what to do. 

Renaming the column reading functions is not a big task on its own but it introduces **breaking changes** both for this library and the downstream libraries, specificially the ionide [syntax analyzer and type-checker](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) which is built to detect a specific syntax of this library to get everything working, 

Alright, I will break this thing apart and make it better again. Lets hope not too many people will be angry from yet another major upgrade ;)

**Comment by ericsampson** [comment]
What about just adding aliases @Zaid-Ajaj ? That wouldn't break the interface...

**Comment by Zaid-Ajaj** [comment]
@ericsampson It has been upgraded to v3.0 with the new function names

> What about just adding aliases

Then there be too many functions that do the same thing. Especially the analyzer will be trying to recommend too many functions that do the same thing essentially

**Comment by ericsampson** [comment]
Zaid, thank you! I feel bad causing extra work and pain. But thank you! 🍰

**Comment by Zaid-Ajaj** [comment]
No worries it is for the best :rocket: :smile:

**Pull request merged**
